#端口配置
server:
  port: 8102
  servlet:
    encoding:
      force: true
      session:
        tracking-modes: cookie
spring:
  application:
    name: seeho-web-test
#web配置
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  circuitbreaker:
    enabled: true # 开启 feign 断路器支持
  sentinel: #熔断器配置
    enabled: true
  hystrix:
    enabled: false
  httpclient: #不用httpClient
    enabled: false
  okhttp: #用ok http
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000 #连接超时
        readTimeout: 10000 #读取超时
  compression: #开启Gzip压缩
    request:
      enabled: true # 请求开启压缩
      min-request-size: 2048 #最小压缩大小（字符），低于这个值则不压缩
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true # 响应开启压缩

resttemplate:
  sentinel:
    enabled: false
