# 通用运行配置，不依赖环境
server:
  port: 8081
  servlet:
    encoding:
      force: true
    session:
      tracking-modes: cookie
feign:
  circuitbreaker:
    enabled: true
  sentinel:
    enabled: true
  hystrix:
    enabled: false
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true
